title: "NakbaVirality"
description: "NakbaVirality: Multimodal and Textual Virality Prediction in High-Stakes Discourse"
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: "https://forms.gle/ufj2gqRyMrrdDs5f9"
  repository_name: "Registration Open"
markdown:
  kramdown:
    auto_ids: false  # This disables automatic heading IDs

