title: "NakbaVirality"
description: "NakbaVirality: Multimodal and Textual Virality Prediction in High-Stakes Discourse"
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: "https://forms.gle/3hbL8xv8t3rMR9C19"
  repository_name: "Join the competition now!"
markdown:
  kramdown:
    auto_ids: false  # This disables automatic heading IDs

